// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package persistence

import (
	"database/sql"
)

type Feed struct {
	Title       string
	Description sql.NullString
	Link        sql.NullString
	FeedLink    sql.NullString
	Updated     sql.NullTime
}
